from enum import IntEnum


class SureEnum(IntEnum):
    """Sure base enum."""

    def __str__(self) -> str:
        return self.name.title()  # pylint: disable=no-member


class EntityType(SureEnum):
    """Sure Entity Types."""

    PET = 0  # artificial ID, not used by the Sure Petcare API
    HUB = 1  # Hub
    REPEATER = 2  # Repeater
    PET_FLAP = 3  # Pet Door Connect
    FEEDER = 4  # Microchip Pet Feeder Connect
    PROGRAMMER = 5  # Programmer
    CAT_FLAP = 6  # Cat Flap Connect
    FEEDER_LITE = 7  # Feeder Lite
    FELAQUA = 8  # Felaqua Connect


class LockState(SureEnum):
    """Sure Petcare API State IDs."""

    UNLOCKED = 0
    LOCKED_IN = 1
    LOCKED_OUT = 2
    LOCKED_ALL = 3
    CURFEW = 4
    CURFEW_LOCKED = -1
    CURFEW_UNLOCKED = -2
    CURFEW_UNKNOWN = -3


class Location(SureEnum):
    """Sure Locations."""

    INSIDE = 1
    OUTSIDE = 2
    UNKNOWN = -1


class FoodType(SureEnum):
    """Sure Food Types."""

    WET = 1
    DRY = 2
    BOTH = 3
    UNKNOWN = -1


class BowlPosition(SureEnum):
    """Sure Feeder Bowl side."""

    LEFT = 0
    RIGHT = 1


class Species(SureEnum):
    """Species of the pet."""

    CAT = 1
    DOG = 2


class TimelineEvent(SureEnum):
    """Sure timeline event types."""

    BATTERY_LOW = 1
    FOOD_FILLED = 21
    EAT = 22
    FEEDER_TARE = 24
    DRINK = 29
    REMINDER_FRESH_WATER = 32
    ANONYMOUS_DRINK = 34

class TimeZonesLocal(SureEnum):
    """Timezones"""

    Africa/Abidjan =   1
    Africa/Accra =   2
    Africa/Addis_Ababa =   3
    Africa/Algiers =   4
    Africa/Asmara =   5
    Africa/Bamako =   6
    Africa/Bangui =   7
    Africa/Banjul =   8
    Africa/Bissau =   9
    Africa/Blantyre =   10
    Africa/Brazzaville =   11
    Africa/Bujumbura =   12
    Africa/Cairo =   13
    Africa/Casablanca =   14
    Africa/Ceuta =   15
    Africa/Conakry =   16
    Africa/Dakar =   17
    Africa/Dar_es_Salaam =   18
    Africa/Djibouti =   19
    Africa/Douala =   20
    Africa/El_Aaiun =   21
    Africa/Freetown =   22
    Africa/Gaborone =   23
    Africa/Harare =   24
    Africa/Johannesburg =   25
    Africa/Juba =   26
    Africa/Kampala =   27
    Africa/Khartoum =   28
    Africa/Kigali =   29
    Africa/Kinshasa =   30
    Africa/Lagos =   31
    Africa/Libreville =   32
    Africa/Lome =   33
    Africa/Luanda =   34
    Africa/Lubumbashi =   35
    Africa/Lusaka =   36
    Africa/Malabo =   37
    Africa/Maputo =   38
    Africa/Maseru =   39
    Africa/Mbabane =   40
    Africa/Mogadishu =   41
    Africa/Monrovia =   42
    Africa/Nairobi =   43
    Africa/Ndjamena =   44
    Africa/Niamey =   45
    Africa/Nouakchott =   46
    Africa/Ouagadougou =   47
    Africa/Porto-Novo =   48
    Africa/Sao_Tome =   49
    Africa/Tripoli =   50
    Africa/Tunis =   51
    Africa/Windhoek =   52
    America/Adak =   53
    America/Anchorage =   54
    America/Anguilla =   55
    America/Antigua =   56
    America/Araguaina =   57
    America/Argentina/Buenos_Aires =   58
    America/Argentina/Catamarca =   59
    America/Argentina/Cordoba =   60
    America/Argentina/Jujuy =   61
    America/Argentina/La_Rioja =   62
    America/Argentina/Mendoza =   63
    America/Argentina/Rio_Gallegos =   64
    America/Argentina/Salta =   65
    America/Argentina/San_Juan =   66
    America/Argentina/San_Luis =   67
    America/Argentina/Tucuman =   68
    America/Argentina/Ushuaia =   69
    America/Aruba =   70
    America/Asuncion =   71
    America/Atikokan =   72
    America/Bahia =   73
    America/Bahia_Banderas =   74
    America/Barbados =   75
    America/Belem =   76
    America/Belize =   77
    America/Blanc-Sablon =   78
    America/Boa_Vista =   79
    America/Bogota =   80
    America/Boise =   81
    America/Cambridge_Bay =   82
    America/Campo_Grande =   83
    America/Cancun =   84
    America/Caracas =   85
    America/Cayenne =   86
    America/Cayman =   87
    America/Chicago =   88
    America/Chihuahua =   89
    America/Costa_Rica =   90
    America/Creston =   91
    America/Cuiaba =   92
    America/Curacao =   93
    America/Danmarkshavn =   94
    America/Dawson =   95
    America/Dawson_Creek =   96
    America/Denver =   97
    America/Detroit =   98
    America/Dominica =   99
    America/Edmonton =   100
    America/Eirunepe =   101
    America/El_Salvador =   102
    America/Fort_Nelson =   103
    America/Fortaleza =   104
    America/Glace_Bay =   105
    America/Godthab =   106
    America/Goose_Bay =   107
    America/Grand_Turk =   108
    America/Grenada =   109
    America/Guadeloupe =   110
    America/Guatemala =   111
    America/Guayaquil =   112
    America/Guyana =   113
    America/Halifax =   114
    America/Havana =   115
    America/Hermosillo =   116
    America/Indiana/Indianapolis =   117
    America/Indiana/Knox =   118
    America/Indiana/Marengo =   119
    America/Indiana/Petersburg =   120
    America/Indiana/Tell_City =   121
    America/Indiana/Vevay =   122
    America/Indiana/Vincennes =   123
    America/Indiana/Winamac =   124
    America/Inuvik =   125
    America/Iqaluit =   126
    America/Jamaica =   127
    America/Juneau =   128
    America/Kentucky/Louisville =   129
    America/Kentucky/Monticello =   130
    America/Kralendijk =   131
    America/La_Paz =   132
    America/Lima =   133
    America/Los_Angeles =   134
    America/Lower_Princes =   135
    America/Maceio =   136
    America/Managua =   137
    America/Manaus =   138
    America/Marigot =   139
    America/Martinique =   140
    America/Matamoros =   141
    America/Mazatlan =   142
    America/Menominee =   143
    America/Merida =   144
    America/Metlakatla =   145
    America/Mexico_City =   146
    America/Miquelon =   147
    America/Moncton =   148
    America/Monterrey =   149
    America/Montevideo =   150
    America/Montserrat =   151
    America/Nassau =   152
    America/New_York =   153
    America/Nipigon =   154
    America/Nome =   155
    America/Noronha =   156
    America/North_Dakota/Beulah =   157
    America/North_Dakota/Center =   158
    America/North_Dakota/New_Salem =   159
    America/Ojinaga =   160
    America/Panama =   161
    America/Pangnirtung =   162
    America/Paramaribo =   163
    America/Phoenix =   164
    America/Port-au-Prince =   165
    America/Port_of_Spain =   166
    America/Porto_Velho =   167
    America/Puerto_Rico =   168
    America/Punta_Arenas =   169
    America/Rainy_River =   170
    America/Rankin_Inlet =   171
    America/Recife =   172
    America/Regina =   173
    America/Resolute =   174
    America/Rio_Branco =   175
    America/Santarem =   176
    America/Santiago =   177
    America/Santo_Domingo =   178
    America/Sao_Paulo =   179
    America/Scoresbysund =   180
    America/Sitka =   181
    America/St_Barthelemy =   182
    America/St_Johns =   183
    America/St_Kitts =   184
    America/St_Lucia =   185
    America/St_Thomas =   186
    America/St_Vincent =   187
    America/Swift_Current =   188
    America/Tegucigalpa =   189
    America/Thule =   190
    America/Thunder_Bay =   191
    America/Tijuana =   192
    America/Toronto =   193
    America/Tortola =   194
    America/Vancouver =   195
    America/Whitehorse =   196
    America/Winnipeg =   197
    America/Yakutat =   198
    America/Yellowknife =   199
    Antarctica/Casey =   200
    Antarctica/Davis =   201
    Antarctica/DumontDUrville =   202
    Antarctica/Macquarie =   203
    Antarctica/Mawson =   204
    Antarctica/McMurdo =   205
    Antarctica/Palmer =   206
    Antarctica/Rothera =   207
    Antarctica/Syowa =   208
    Antarctica/Troll =   209
    Antarctica/Vostok =   210
    Asia/Aden =   211
    Asia/Almaty =   212
    Asia/Amman =   213
    Asia/Anadyr =   214
    Asia/Aqtau =   215
    Asia/Aqtobe =   216
    Asia/Ashgabat =   217
    Asia/Atyrau =   218
    Asia/Baghdad =   219
    Asia/Bahrain =   220
    Asia/Baku =   221
    Asia/Bangkok =   222
    Asia/Barnaul =   223
    Asia/Beirut =   224
    Asia/Bishkek =   225
    Asia/Brunei =   226
    Asia/Chita =   227
    Asia/Choibalsan =   228
    Asia/Colombo =   229
    Asia/Damascus =   230
    Asia/Dhaka =   231
    Asia/Dili =   232
    Asia/Dubai =   233
    Asia/Dushanbe =   234
    Asia/Famagusta =   235
    Asia/Gaza =   236
    Asia/Hebron =   237
    Asia/Ho_Chi_Minh =   238
    Asia/Hong_Kong =   239
    Asia/Hovd =   240
    Asia/Irkutsk =   241
    Asia/Jakarta =   242
    Asia/Jayapura =   243
    Asia/Jerusalem =   244
    Asia/Kabul =   245
    Asia/Kamchatka =   246
    Asia/Karachi =   247
    Asia/Kathmandu =   248
    Asia/Khandyga =   249
    Asia/Kolkata =   250
    Asia/Krasnoyarsk =   251
    Asia/Kuala_Lumpur =   252
    Asia/Kuching =   253
    Asia/Kuwait =   254
    Asia/Macau =   255
    Asia/Magadan =   256
    Asia/Makassar =   257
    Asia/Manila =   258
    Asia/Muscat =   259
    Asia/Nicosia =   260
    Asia/Novokuznetsk =   261
    Asia/Novosibirsk =   262
    Asia/Omsk =   263
    Asia/Oral =   264
    Asia/Phnom_Penh =   265
    Asia/Pontianak =   266
    Asia/Pyongyang =   267
    Asia/Qatar =   268
    Asia/Qyzylorda =   269
    Asia/Riyadh =   270
    Asia/Sakhalin =   271
    Asia/Samarkand =   272
    Asia/Seoul =   273
    Asia/Shanghai =   274
    Asia/Singapore =   275
    Asia/Srednekolymsk =   276
    Asia/Taipei =   277
    Asia/Tashkent =   278
    Asia/Tbilisi =   279
    Asia/Tehran =   280
    Asia/Thimphu =   281
    Asia/Tokyo =   282
    Asia/Tomsk =   283
    Asia/Ulaanbaatar =   284
    Asia/Urumqi =   285
    Asia/Ust-Nera =   286
    Asia/Vientiane =   287
    Asia/Vladivostok =   288
    Asia/Yakutsk =   289
    Asia/Yangon =   290
    Asia/Yekaterinburg =   291
    Asia/Yerevan =   292
    Atlantic/Azores =   293
    Atlantic/Bermuda =   294
    Atlantic/Canary =   295
    Atlantic/Cape_Verde =   296
    Atlantic/Faroe =   297
    Atlantic/Madeira =   298
    Atlantic/Reykjavik =   299
    Atlantic/South_Georgia =   300
    Atlantic/St_Helena =   301
    Atlantic/Stanley =   302
    Australia/Adelaide =   303
    Australia/Brisbane =   304
    Australia/Broken_Hill =   305
    Australia/Currie =   306
    Australia/Darwin =   307
    Australia/Eucla =   308
    Australia/Hobart =   309
    Australia/Lindeman =   310
    Australia/Lord_Howe =   311
    Australia/Melbourne =   312
    Australia/Perth =   313
    Australia/Sydney =   314
    Europe/Amsterdam =   315
    Europe/Andorra =   316
    Europe/Astrakhan =   317
    Europe/Athens =   318
    Europe/Belgrade =   319
    Europe/Berlin =   320
    Europe/Bratislava =   321
    Europe/Brussels =   322
    Europe/Bucharest =   323
    Europe/Budapest =   324
    Europe/Busingen =   325
    Europe/Chisinau =   326
    Europe/Copenhagen =   327
    Europe/Dublin =   328
    Europe/Gibraltar =   329
    Europe/Guernsey =   330
    Europe/Helsinki =   331
    Europe/Isle_of_Man =   332
    Europe/Istanbul =   333
    Europe/Jersey =   334
    Europe/Kaliningrad =   335
    Europe/Kiev =   336
    Europe/Kirov =   337
    Europe/Lisbon =   338
    Europe/Ljubljana =   339
    Europe/London =   340
    Europe/Luxembourg =   341
    Europe/Madrid =   342
    Europe/Malta =   343
    Europe/Mariehamn =   344
    Europe/Minsk =   345
    Europe/Monaco =   346
    Europe/Moscow =   347
    Europe/Oslo =   348
    Europe/Paris =   349
    Europe/Podgorica =   350
    Europe/Prague =   351
    Europe/Riga =   352
    Europe/Rome =   353
    Europe/Samara =   354
    Europe/San_Marino =   355
    Europe/Sarajevo =   356
    Europe/Saratov =   357
    Europe/Simferopol =   358
    Europe/Skopje =   359
    Europe/Sofia =   360
    Europe/Stockholm =   361
    Europe/Tallinn =   362
    Europe/Tirane =   363
    Europe/Ulyanovsk =   364
    Europe/Uzhgorod =   365
    Europe/Vaduz =   366
    Europe/Vatican =   367
    Europe/Vienna =   368
    Europe/Vilnius =   369
    Europe/Volgograd =   370
    Europe/Warsaw =   371
    Europe/Zagreb =   372
    Europe/Zaporozhye =   373
    Europe/Zurich =   374
    Indian/Antananarivo =   375
    Indian/Chagos =   376
    Indian/Christmas =   377
    Indian/Cocos =   378
    Indian/Comoro =   379
    Indian/Kerguelen =   380
    Indian/Mahe =   381
    Indian/Maldives =   382
    Indian/Mauritius =   383
    Indian/Mayotte =   384
    Indian/Reunion =   385
    Pacific/Apia =   386
    Pacific/Auckland =   387
    Pacific/Bougainville =   388
    Pacific/Chatham =   389
    Pacific/Chuuk =   390
    Pacific/Easter =   391
    Pacific/Efate =   392
    Pacific/Enderbury =   393
    Pacific/Fakaofo =   394
    Pacific/Fiji =   395
    Pacific/Funafuti =   396
    Pacific/Galapagos =   397
    Pacific/Gambier =   398
    Pacific/Guadalcanal =   399
    Pacific/Guam =   400
    Pacific/Honolulu =   401
    Pacific/Kiritimati =   402
    Pacific/Kosrae =   403
    Pacific/Kwajalein =   404
    Pacific/Majuro =   405
    Pacific/Marquesas =   406
    Pacific/Midway =   407
    Pacific/Nauru =   408
    Pacific/Niue =   409
    Pacific/Norfolk =   410
    Pacific/Noumea =   411
    Pacific/Pago_Pago =   412
    Pacific/Palau =   413
    Pacific/Pitcairn =   414
    Pacific/Pohnpei =   415
    Pacific/Port_Moresby =   416
    Pacific/Rarotonga =   417
    Pacific/Saipan =   418
    Pacific/Tahiti =   419
    Pacific/Tarawa =   420
    Pacific/Tongatapu =   421
    Pacific/Wake =   422
    Pacific/Wallis =   423
    UTC = 42
